// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbdtgqmzoduommzcutgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiZHRncW16b2R1b21temN1dGd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4Nzk3MzQsImV4cCI6MjA2NDQ1NTczNH0.wCcRg6IOzVAQEnw2w7hwuAzL8-pcZsDfPYXwnzd5zb8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);